config/routes.rb
Rails.application.routes.draw do
  
  # Webhook routes
  get "webhooks/uninstall"
  post "webhooks/uninstall"

  # Shopify routes
  get 'shopify/authorize' => 'shopify#authorize'
  post 'shopify/authorize' => 'shopify#authorize'
  get 'shopify/install' => 'shopify#install'
  post 'shopify/install' => 'shopify#install'

  get 'dashboard/index' => 'dashboard#index'

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  resources :orders do
    collection do
      get 'import'
    end
  end
  
  resources :products do
    collection do
      get 'import'
    end
    resources :variants  
  end

  resources :accounts do
    member do
      get 'test_connection'
    end
  end

  post "create_contest" => 'dashboard#create_contest'

  root 'dashboard#index'
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :account

  # This method constructs the query based on
  # the passed-in parameters
  def self.candidate_list(params={})
    params[:sort] ||= "order_date asc"
    orders = order(params[:sort]).includes(:order_items)

    if params[:max_results].present?
      orders = orders.limit(params[:max_results].to_i)
    end

    if params[:product_id].present?
      orders = orders.where("order_items.shopify_product_id" => params[:product_id].to_i)
    end

    if params[:start_date].present?
      orders = orders.where(["orders.order_date >= ?", params[:start_date]])
    end

    if params[:end_date].present?
      orders = orders.where(["orders.order_date <= ?", params[:end_date]])
    end

    # .pluck returns an array containing the specified field
    return orders.pluck(:id).uniq
  end  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # GET /orders/import
  # GET /orders/import.json
  def import

    # For now we'll use the first Account in the database
    account = Account.first

    # Connect to Shopify
    shopify_integration = ShopifyIntegration.new(api_key: account.shopify_api_key,
                                                 shared_secret: account.shopify_shared_secret,
                                                 url: account.shopify_account_url,
                                                 password: account.shopify_password)

    respond_to do |format|
      if shopify_integration.connect
        # Import Products to ensure we are up to date
        shopify_integration.import_products
        result = shopify_integration.import_orders
        format.html { redirect_to ({action: :index}), notice: "#{result[:created].to_i} created, #{result[:failed]} failed." }
        format.json { render json: "#{result[:created].to_i} created, #{result[:failed]} failed." }
      else
        format.html { redirect_to ({action: :index}), alert: "Unable to connect to Shopify" }
        format.json { render json: "Unable to connect to Shopify", status: :unprocessable_entity }
      end
    end

  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:number, :email, :first_name, :last_name, :shopify_order_id, :order_date, :total, :line_item_count, :financial_status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @order.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :number, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :first_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :shopify_order_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :shopify_order_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :order_date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :order_date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :total, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :total, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :line_item_count, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :line_item_count, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :financial_status, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :financial_status, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @order, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing order</h1>
</div>

<%= render 'form' %>

app/views/orders/index.html.erb
<div class="page-header">
  <%= link_to new_order_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Order
  <% end %>
  <h1>Listing orders</h1>
  <p><a href="<%= import_orders_path %>">Import Orders</a></p>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Number</th>
            <th>Email</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Shopify order</th>
            <th>Order date</th>
            <th>Total</th>
            <th>Line item count</th>
            <th>Financial status</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @orders) do |order| %>
            <td><%= order.number %></td>
            <td><%= order.email %></td>
            <td><%= order.first_name %></td>
            <td><%= order.last_name %></td>
            <td><%= order.shopify_order_id %></td>
            <td><%= order.order_date %></td>
            <td><%= order.total %></td>
            <td><%= order.line_item_count %></td>
            <td><%= order.financial_status %></td>
            <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New order</h1>
</div>

<%= render 'form' %>

app/views/orders/show.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_order_path(@order), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show order</h1>
</div>

<dl class="dl-horizontal">
  <dt>Number:</dt>
  <dd><%= @order.number %></dd>

  <dt>Email:</dt>
  <dd><%= @order.email %></dd>

  <dt>First name:</dt>
  <dd><%= @order.first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @order.last_name %></dd>

  <dt>Shopify order:</dt>
  <dd><%= @order.shopify_order_id %></dd>

  <dt>Order date:</dt>
  <dd><%= @order.order_date %></dd>

  <dt>Total:</dt>
  <dd><%= @order.total %></dd>

  <dt>Line item count:</dt>
  <dd><%= @order.line_item_count %></dd>

  <dt>Financial status:</dt>
  <dd><%= @order.financial_status %></dd>

</dl>