config/routes.rb
Rails.application.routes.draw do
  
  # Webhook routes
  get "webhooks/uninstall"
  post "webhooks/uninstall"

  # Shopify routes
  get 'shopify/authorize' => 'shopify#authorize'
  post 'shopify/authorize' => 'shopify#authorize'
  get 'shopify/install' => 'shopify#install'
  post 'shopify/install' => 'shopify#install'

  get 'dashboard/index' => 'dashboard#index'

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  resources :orders do
    collection do
      get 'import'
    end
  end
  
  resources :products do
    collection do
      get 'import'
    end
    resources :variants  
  end

  resources :accounts do
    member do
      get 'test_connection'
    end
  end

  post "create_contest" => 'dashboard#create_contest'

  root 'dashboard#index'
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  before_action :set_product
  before_action :set_variant, only: [:show, :edit, :update, :destroy]

  # GET /variants
  # GET /variants.json
  def index
    @variants = Variant.all
  end

  # GET /variants/1
  # GET /variants/1.json
  def show
  end

  # GET /variants/new
  def new
    @variant = Variant.new
  end

  # GET /variants/1/edit
  def edit
  end

  # POST /variants
  # POST /variants.json
  def create
    @variant = Variant.new(variant_params)

    respond_to do |format|
      if @variant.save
        format.html { redirect_to @variant, notice: 'Variant was successfully created.' }
        format.json { render :show, status: :created, location: @variant }
      else
        format.html { render :new }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variants/1
  # PATCH/PUT /variants/1.json
  def update
    respond_to do |format|
      if @variant.update(variant_params)
        format.html { redirect_to @variant, notice: 'Variant was successfully updated.' }
        format.json { render :show, status: :ok, location: @variant }
      else
        format.html { render :edit }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variants/1
  # DELETE /variants/1.json
  def destroy
    @variant.destroy
    respond_to do |format|
      format.html { redirect_to variants_url, notice: 'Variant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variant
      @variant = Variant.find(params[:id])
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variant_params
      params.require(:variant).permit(:product_id, :shopify_variant_id, :option2, :option2, :option3, :sku, :barcode, :price, :last_shopify_sync)
    end
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/variants/_form.html.erb
<%= form_for(@variant, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @variant.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@variant.errors.count, "error") %> prohibited this variant from being saved:</h4>

      <ul>
      <% @variant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :product_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :product_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :shopify_variant_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :shopify_variant_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :option2, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :option2, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :option2, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :option2, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :option3, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :option3, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sku, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :sku, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :barcode, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :barcode, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_shopify_sync, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :last_shopify_sync, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/variants/edit.html.erb
<div class="page-header">
  <%= link_to variants_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @variant, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing variant</h1>
</div>

<%= render 'form' %>

app/views/variants/index.html.erb
<div class="page-header">
  <%= link_to new_variant_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Variant
  <% end %>
  <h1>Listing variants</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Product</th>
            <th>Shopify variant</th>
            <th>Option2</th>
            <th>Option2</th>
            <th>Option3</th>
            <th>Sku</th>
            <th>Barcode</th>
            <th>Price</th>
            <th>Last shopify sync</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @variants) do |variant| %>
            <td><%= variant.product_id %></td>
            <td><%= variant.shopify_variant_id %></td>
            <td><%= variant.option2 %></td>
            <td><%= variant.option2 %></td>
            <td><%= variant.option3 %></td>
            <td><%= variant.sku %></td>
            <td><%= variant.barcode %></td>
            <td><%= variant.price %></td>
            <td><%= variant.last_shopify_sync %></td>
            <td><%= link_to 'Show', variant %></td>
        <td><%= link_to 'Edit', edit_variant_path(variant) %></td>
        <td><%= link_to 'Destroy', variant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/variants/new.html.erb
<div class="page-header">
  <%= link_to variants_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New variant</h1>
</div>

<%= render 'form' %>

app/views/variants/show.html.erb
<div class="page-header">
  <%= link_to variants_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_variant_path(@variant), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show variant</h1>
</div>

<dl class="dl-horizontal">
  <dt>Product:</dt>
  <dd><%= @variant.product_id %></dd>

  <dt>Shopify variant:</dt>
  <dd><%= @variant.shopify_variant_id %></dd>

  <dt>Option2:</dt>
  <dd><%= @variant.option2 %></dd>

  <dt>Option2:</dt>
  <dd><%= @variant.option2 %></dd>

  <dt>Option3:</dt>
  <dd><%= @variant.option3 %></dd>

  <dt>Sku:</dt>
  <dd><%= @variant.sku %></dd>

  <dt>Barcode:</dt>
  <dd><%= @variant.barcode %></dd>

  <dt>Price:</dt>
  <dd><%= @variant.price %></dd>

  <dt>Last shopify sync:</dt>
  <dd><%= @variant.last_shopify_sync %></dd>

</dl>