config/routes.rb
Rails.application.routes.draw do
  
  # Webhook routes
  get "webhooks/uninstall"
  post "webhooks/uninstall"

  # Shopify routes
  get 'shopify/authorize' => 'shopify#authorize'
  post 'shopify/authorize' => 'shopify#authorize'
  get 'shopify/install' => 'shopify#install'
  post 'shopify/install' => 'shopify#install'

  get 'dashboard/index' => 'dashboard#index'

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  resources :orders do
    collection do
      get 'import'
    end
  end
  
  resources :products do
    collection do
      get 'import'
    end
    resources :variants  
  end

  resources :accounts do
    member do
      get 'test_connection'
    end
  end

  post "create_contest" => 'dashboard#create_contest'

  root 'dashboard#index'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :variants
  belongs_to :account
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = current_account.products.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_account.products.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_account.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /products/import
  # GET /products/import.json
  def import
    # Connect to Shopify
    shopify_integration = ShopifyIntegration.new(
      url: current_account.shopify_account_url,
      password: current_account.shopify_password,
      account_id: current_account.id
    )

    respond_to do |format|
      shopify_integration.connect
      result = shopify_integration.import_products
      format.html { redirect_to ({action: :index}), notice: "#{result[:created].to_i} created, #{result[:updated]} updated, #{result[:failed]} failed." }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = current_account.products.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :shopify_product_id, :last_shopify_sync)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :shopify_product_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :shopify_product_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_shopify_sync, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :last_shopify_sync, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="page-header">
  <%= link_to products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @product, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing product</h1>
</div>

<%= render 'form' %>

app/views/products/index.html.erb
<div class="page-header">
  <%= link_to new_product_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Product
  <% end %>
  <h1>Listing products</h1>
  <p><a href="<%= import_products_path %>">Import Products</a></p>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Shopify product</th>
            <th>Last shopify sync</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @products) do |product| %>
            <td><%= product.name %></td>
            <td><%= product.shopify_product_id %></td>
            <td><%= product.last_shopify_sync %></td>
            <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<div class="page-header">
  <%= link_to products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New product</h1>
</div>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="page-header">
  <%= link_to products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_product_path(@product), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show product</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @product.name %></dd>

  <dt>Shopify product:</dt>
  <dd><%= @product.shopify_product_id %></dd>

  <dt>Last shopify sync:</dt>
  <dd><%= @product.last_shopify_sync %></dd>

</dl>